exports.handler = async (event, context) => {
  // Only allow POST requests
  if (event.httpMethod !== 'POST') {
    return {
      statusCode: 405,
      body: JSON.stringify({ error: 'Method Not Allowed' })
    };
  }

  try {
    // Parse the incoming JSON payload from the frontend
    const payload = JSON.parse(event.body);

    // The secure Webhook URL generated by Microsoft Power Automate
    // (This is hidden from the public frontend because it runs on Netlify's backend servers)
    const MICROSOFT_WEBHOOK_URL = "https://defaultb337571c41914dabbb413a06a96cf9.04.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/e1ebada36cb047c69201569262fda807/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=SFlf34zLpaeF0bZ7Wu2ECd9METsAyCVWOGS7r_dltWI";

    // Forward the data to Microsoft
    const response = await fetch(MICROSOFT_WEBHOOK_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        name: payload.name || 'Not provided',
        email: payload.email || 'Not provided',
        company: payload.company || 'Not provided',
        message: payload.message || 'No message provided'
      })
    });

    if (!response.ok) {
      throw new Error(`Microsoft Webhook responded with status: ${response.status}`);
    }

    return {
      statusCode: 200,
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ success: true, message: 'Lead submitted to Microsoft successfully.' })
    };

  } catch (error) {
    console.error('Error submitting contact form:', error);
    return {
      statusCode: 500,
      body: JSON.stringify({ error: 'Failed to process submission' })
    };
  }
};
